LAF_LIGHT=org.kde.custom.light
LAF_DARK=org.kde.custom.dark
KVANTUM_LIGHT=catppuccin-latte-blue
KVANTUM_DARK=catppuccin-frappe-blue
ICON_LIGHT=Qogir-Light
ICON_DARK=Qogir-Dark
PLASMA_CHANGEICONS=/usr/lib/plasma-changeicons
GTK_LIGHT=catppuccin-latte-blue-standard+default
GTK_DARK=catppuccin-frappe-blue-standard+default
COLOR_LIGHT=
COLOR_DARK=
STYLE_LIGHT=breeze-light
STYLE_DARK=breeze-dark
DECORATION_LIGHT=__aurorae__svg__CatppuccinLatte-Modern
DECORATION_DARK=__aurorae__svg__CatppuccinFrappe-Modern
CURSOR_LIGHT=Breeze_Light
CURSOR_DARK=breeze_cursors
KONSOLE_LIGHT=
KONSOLE_DARK=
SPLASH_LIGHT=
SPLASH_DARK=
SDDM_LIGHT=
SDDM_DARK=
APPSTYLE_LIGHT=kvantum
APPSTYLE_DARK=kvantum
WALLPAPER=
WP_SOURCE_LIGHT=
WP_SOURCE_DARK=
SCRIPT_LIGHT=
SCRIPT_DARK=
CUSTOM_THEME_LIGHT=org.kde.custom.light
CUSTOM_THEME_DARK=org.kde.custom.dark
BASE_THEME_LIGHT=Catppuccin-Latte-Blue
BASE_THEME_DARK=Catppuccin-Frappe-Blue
THEME_INSTALL_GLOBAL=true
WALLPAPER_BASE=
ICON_LIGHT_MOVED_FROM=
ICON_DARK_MOVED_FROM=
CURSOR_LIGHT_MOVED_FROM=
CURSOR_DARK_MOVED_FROM=
INSTALL_GLOBAL=true
PUSH_TO_USERS=false
SET_SYSTEM_DEFAULTS=true
COPY_DESKTOP_LAYOUT=true
INSTALL_CLI=false
INSTALL_WIDGET=false
INSTALL_SHORTCUT=false
FLATPAK_PREV_OVERRIDES=QT_STYLE_OVERRIDE=
